# Minecraft Object Detection Dataset
path: datasets/minecraft
train: train
val: val
test: test

nc: 17
names: ['bee', 'chicken', 'cow', 'creeper', 'enderman', 'fox', 'frog', 'ghast', 
        'goat', 'llama', 'pig', 'sheep', 'skeleton', 'spider', 'turtle', 'wolf', 'zombie']
